version: 2
updates:
- package-ecosystem: npm
  directory: "/docs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/example"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/example/functions"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
